// generated by Fast Light User Interface Designer (fluid) version 1.0108

#include <libintl.h>
#include "stygmaboutui.h"
//Copyright(c) 2006 Josep Andreu (holborn)
//License GNU/GPL version 2

void about::cb_aboutwin_i(Fl_Double_Window*, void*) {
  aboutwin->clear();
aboutwin->hide();
wabout=0;
delete aboutwin;
}
void about::cb_aboutwin(Fl_Double_Window* o, void* v) {
  ((about*)(o->user_data()))->cb_aboutwin_i(o,v);
}

#include <FL/Fl_Pixmap.H>
static const char *idata_stygmicon128[] = {
"128 128 186 2",
"Qt c None",
"Qt c None",
"at c #070b16",
"ae c #070b17",
"am c #070c18",
"ag c #070c19",
"af c #080d1a",
"ax c #080d1b",
"as c #080e1c",
"ah c #090e1d",
"ab c #090f1e",
"ad c #09101f",
"#3 c #0a1020",
"aq c #0a1021",
"#4 c #0a1122",
"ai c #0b1123",
"#5 c #0b1224",
"#6 c #0b1225",
"#7 c #0b1326",
"#Y c #0c1327",
"#8 c #0c1428",
"#U c #0c1429",
"#Z c #0d152a",
"#S c #0d152b",
"aj c #0d162c",
"#R c #0e162d",
"#T c #0e172e",
"#L c #0e172f",
"#M c #0f1830",
"#N c #0f1831",
"#K c #0f1932",
"#F c #101a33",
"#Q c #101a34",
"#J c #101b35",
"#2 c #111b37",
"#O c #111c38",
"#9 c #111c39",
"ak c #121d3a",
".v c #121e3b",
"aa c #131e3c",
".s c #131f3e",
".w c #131f3f",
".x c #142040",
".u c #142141",
"#G c #142143",
".j c #152244",
".k c #152345",
".y c #162347",
"#V c #162448",
".f c #162549",
".h c #17254a",
".X c #17264c",
".Y c #18274d",
".i c #18274f",
".W c #192850",
".Z c #192951",
"#p c #192953",
".8 c #1a2a54",
"#. c #1a2b56",
".J c #1b2c57",
".U c #1b2c58",
"#P c #1c2d5a",
"#y c #1c2e5b",
"#c c #1d2f5d",
".z c #1d2f5e",
".I c #1e3060",
".9 c #1e3161",
".t c #1f3262",
".V c #203363",
"#k c #213464",
"#o c #223565",
".H c #243666",
"#z c #253767",
"#i c #263868",
".l c #273969",
"#j c #283a6a",
"#l c #293b6b",
".r c #2a3d6c",
".g c #2b3e6d",
".L c #2c3f6e",
"#D c #2e4070",
"#b c #2f4171",
"#a c #304272",
"#H c #314373",
"#m c #324574",
".K c #344675",
"#d c #354776",
"## c #364877",
".0 c #374978",
"#n c #394b79",
".G c #3a4c7a",
".T c #3b4d7b",
"#h c #3d4e7c",
"#q c #3e507e",
"#0 c #3f517f",
"#C c #415280",
".o c #425381",
".7 c #435582",
"#I c #455683",
"#w c #465784",
".b c #475985",
".S c #495a87",
"#W c #4a5b88",
".E c #4c5d89",
"#x c #4d5e8a",
"#1 c #4f5f8b",
".e c #50618c",
".F c #52628d",
".6 c #53648f",
"#v c #556590",
"a. c #566691",
".m c #586892",
"#B c #596993",
".a c #5b6b94",
"a# c #5c6c96",
".C c #5e6e97",
"an c #606f98",
".Q c #617199",
"#A c #63729a",
"ay c #64749c",
"ao c #66759d",
".D c #68779e",
".R c #69789f",
"#u c #6b7aa0",
".q c #6d7ba2",
"ap c #6e7da3",
".P c #707fa4",
".B c #7280a5",
".p c #7482a6",
"aA c #7583a8",
".5 c #7785a9",
"ac c #7987aa",
"al c #7b88ab",
"az c #7d8aad",
".O c #7e8cae",
"#r c #808daf",
"aw c #828fb0",
".n c #8491b2",
"ar c #8692b3",
".4 c #8894b4",
".A c #8a96b6",
"#X c #8b97b7",
".M c #8d99b8",
"au c #8f9bb9",
".2 c #919dbb",
"#g c #939ebc",
".d c #95a0bd",
"#e c #97a2bf",
".3 c #99a4c0",
"av c #9ba6c1",
"#f c #9da7c2",
".N c #9fa9c4",
"aY c #a1abc5",
"aB c #a3adc6",
"#s c #a5afc8",
".1 c #a7b1c9",
"aK c #a9b3ca",
"#t c #abb4cc",
".# c #adb6cd",
"aG c #b0b8ce",
"aD c #b2bad0",
"aO c #b4bcd1",
"aS c #b6bed3",
"aV c #b8c0d4",
"a3 c #bac2d5",
"aT c #bdc4d7",
"#E c #bfc6d8",
"aW c #c1c8d9",
"a0 c #c3cadb",
"a1 c #c5ccdc",
"aN c #c8cede",
"aE c #cad0df",
"aP c #ccd2e0",
"aZ c #ced4e2",
"aC c #d1d6e3",
"a2 c #d3d8e5",
"aX c #d5dae6",
"aL c #d8dce7",
"aF c #dadee9",
"aH c #dce0ea",
"aM c #dfe2ec",
"aI c #e1e4ed",
"aJ c #e3e7ee",
"aQ c #e6e9f0",
"aR c #e8ebf1",
"aU c #ebedf3",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.a.b.cQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQt.d.e.f.g.f.h.i.j.k.f.l.mQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQt.n.o.p.q.r.s.t.f.u.v.v.v.w.x.x.u.k.y.f.z.eQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.A.B.C.D.\
E.F.G.l.H.I.i.J.l.K.H.f.s.w.u.j.k.k.k.y.h.i.L.MQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.N.O.N.P.Q.R.e.S.T.r.H.z.U.\
J.V.V.W.l.K.K.r.l.l.g.z.f.u.j.k.k.k.k.f.X.Y.Z.0.NQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.1.2.3.4.P.5.C.6.7.K.l.V.8.W.9.H.i#.##.0.\
V#a#b.U#c.K.0.K.H.o###a.t.h.j.k.k.k.f.Y.W.Z.Z.U#dQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt.c#e#f#g.M.n.q.Q.e#h#a#i.U.t#j.r#k.K.K#i.z.l.K.H.t#l.0#\
m#j#n#m#j.K#h#n.g.K.S.S#h#o.f.k.y.k.f.i#p.8.8.U.z#qQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQt#r.FQt.c#s#t.d.4.A.p#u#v.o.K#b.l#o.H.l.H#l#n#i.I#b##.r.L.T.K.L.z#a.G.0.z#d#\
n#l#a#h#a.L.E#w#a.l#x.E.b#n.t.f.f.f.h.i.8.8.U.U#y#z#vQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.5#h.\
K#k.H.Z#h#A#B#w.K.l.I.U#b.K.T.K.r#h.K.H.0#C.l#n#a.l#b#h#D#k.T#q.G.l.g#h.T###D.\
o.K.l.o.7.o.K.e.E#n#h#w#h#h##.z.h.Y.i.Z.8.J#y#c.z#y.l#xQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#E.5.z#q#.#k.Y#F.w.x.\
f.r#G.W.J.J#..J.J#..J.U.H#b#a#H.I#D#H.H.L#C#n.g#d.V.H#h#q#a#a.o.o#n#m.T.o.G.H.\
T.b.l#a.o#d#j.K#a#a.K#n#h#I.F.K.U.i.i#p.8.U#y.z.z.t.z#h.2QtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.d#a#i#c.i.Y#J.v#K#L#L#M#N#N#O.w#\
P.V.H#O#P#c#c#c#c#y#y.z.9#m.0.T.V#z.o#a#i#q.E.g.7#n.g#m.b#w#j.o.E.E#a.L.S#w#n#\
a#D.l.r.g.H.t.L#a.K###h.o.o.S#h.j.8#p.8.J.U#c.z.I.t.t.t.GQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.N.0.K.z#Q.W#Q#Q#R#S#S#R#T#L#L#L#M#N#N#N#K#J#O#\
c.z.T#U#V.9.9.9.9.t#k.V#o.g.b.e#m.L.T#W.7#n.e.S.0#w.r#m#x.6#w#d.b#w#n.o.b#w#d.\
l.g#c.J.y#O.k.W.K#n#h.b.E.6#v#h.U.U.8.J.U.U#c.z.I.t#o.t.t#dQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQt#X#j.u#N#U#Y#Y#U#Z#Z#Z#S#R#R#R#L#L#M#M#N#N#K#K#K#Q#Q#\
c.9#0#Q#R.9#k#o#o.H.H#i.H.l.o#1#v.e#a.E.e.0#W.e.T.e.7#n.T.S.e.e.E#h.L#c.k#2#L.\
w.L.H.U.t#i.t.U.H.G#I#v.a#B.m.o#p.J#c.U.U#P#c.z.t.V#o.V.t.U.EQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQt.Y#3#4#5#6#7#8#U#Z#Z#Z#S#R#R#L#L#N#N#K#K#K#K#F#F#Q#9.\
Y#k.H#G#c#D.H.g#d#d#m#h.0.g.0.e.a#I#q.o#1#w#n#n##a.a#a..7#D.U.y.v#Q.v.f.U.g.g#\
O.f#a.J.y.saa.W#o#h.S#W.S.E.e#W.uab#c.z#c#c#c.z.t.V.t.t.t.V.tacQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQt.F.iababad#5#Y#Y#8#8#U#Z#Z#S#R#T#L#L#N#K#K#K#K#F#Q#Q#Q.s.\
x#i.z.w.7.e#a#h.G#h#h.T.G#a#b#x.E.7#m#H.o.b#h#m#m#c.k#9#K#O.f#c.H.K.H#..W#h#p.\
Z#O.U#a.r.g.l.J.h.8.o#W.S.Ea.#v.Wae#Q.V#P.z.t.t.9.H#b##.L.t#z.R.MQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQt.##Vafagahabai#Y#Y#8#U#U#Saj#R#R#L#L#M#N#K#F#F#F#Q#Q#Q#2ak#\
9.l#j.k.aal.E#D#D#b#a#a#a#a#m.l#H.F.E#d.K.k.t#m#d#.#y.l.r.l.z#m.6.o.8.Z.j.z#a.\
K.V#2.l.t.faa.8#b.F.e.e#B.F.o.F#oaham#c.l.H.L#d.K.V.z.l.o#v.Qan.p.cQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQt.Oaiafagahab#4#Y#8#8#U#Uaj#R#R#T#L#L#M#N#K#K#K#Q#Q#2#O#O#9.\
w.z#b.r#can.G#b#a#a#H.K.K.K#d#m#i.X.u.K.K.j#K#a.K#h#Ba..8.W.Z.z#a#q.7#0#h.x.Z#\
0.i.8#9#n.oao#A#B.b.G.G.K#0.Cap#d#Uaq#c.l.l.z.H.K.E#q.t.v#T#I.Q#AarQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQt.Vabasatasab#4#Y#8#U#U#Z#Saj#R#T#L#M#N#K#N#N#K#F#Q#O#9ak#9.\
k.f#a#a#H#m#H#a.K.K.K#d#d#m.L.0.0.U#Y.z.7.l#2.Y.0.G.E.T#j.o.e.K#n.o.ba.#w#o.f.\
l.G#C.z#p.b###m.0.m#B.M#n.E.T#h#n#j.V.V.g.7#W#a.8#O#R#6#4#4#2.C.Q#AauQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQt.yadahatasab#3#Y#8#U#U#Z#S#R#T#L#L#M#K#K#K#K#F#Q#Q#Oak.v.v.\
u.w#m.K.K.9#M.x#b.g.r#a.0#n#h.8#n.o#R#Q.F.e#O#R.K.G#o.H###q.K.E.o#h.7.e#x#d.i.\
W.l.K.J#V#d.P.Qav.m#W#x.E#n#a.l.l#n.S#h.t.w#L#S#L#Q#Q#U#4#7#U.I.Q.Cac.cQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQt.p#Ladabaeafab#3#6#8#8#Uaj#R#T#L#L#N#N#N#F#F#Q#Q#Q#O#9.v.vaa.\
s.j.H.0.0.vah#L#n.o#h#h#h#w.E.8#d#W#k#K.l.b.H#9#p#h.K.F.P#i#h.o#H.K#o.z.z.r.g.\
U.U.T#a#a.0.C.7#x.G#H.H.V.L.o.o.r.X#O#L#R#Y#7#6#5#S.8.h#O#M#O#O.o.Q.Q.pQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQt#h#6#3abafagab#3#5#Y#8#Zaj#T#R#L#N#K#K#F#Q#Q#O#2#Oak.vaa.s.w.\
w.X.u#m.G.Uah#U.t#D#w#C.K#a#a.K.T.S.o#U#2.o.o.j#F#q.o.g#k#d.H.t.l#c.H#b.L#a#a#\
a.H#D#C.7#h#h.l.z#o.0.o.K#y.x#K#S#Y#Y#S#K#R#Y#T#U#Y#4#Q.3.S.w#G.f.aana#awQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQt.Wab#3abahatahad#5#8#U#U#T#L#L#N#K#F#Q#2#2#2#O#9ak.v.s.w.w.w.\
x.k.w.v#..T.l.l.r.K.T#h#h#h#h#h#h#q.o.z#R.g.S.K.f#h.7.l.l#n#k#y#o#a#a#a.K#a#d.\
o.o#d.l.z#c#b#q#n.H.f#Q#S#S#L#N#R#Y#U#Yak.Y.Y#6#Y#4aq#3#Y.D.q.j.k.H.Q.C.PQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQt.w#3ai#4abatasab#3#U#Z#R#T#M#K#K#F#Q#Q#2#Oakak.v.vaa.s.w.u.u.\
u.k.8.u.V.k.g.m.E.b#w#w#w#w.7#w.7.o#w.S.t.T.E.C#B.o.e.E.e.6#q#c.H#a.K#q.E#q#a.\
H#c.l#h#C#a.U.w#Kaj#Y#Y#7#5#Y#F.W#Q#6#L#R#6#x.S#Tababafahax#aar.f#V#I.Q.C.OQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQt#5#4aiaiabagasab#3#U#R#T#T#M#K#F#Q#Q#O#9akakaaaa.s.s.w.x.u.j.\
j.k.U#O#a.l.8#..b.E.E.E.E.E.E.ea.ay.R.m.E.F.m#i.H.H#Baza#.m.e.o.e.E.0.l#c.V.K#\
w#h.l.f#F#R#R#N#F#L#8#6#U#5#Kab#S.E.E#R#7#Yah#o.F#Mabahagaxag.j#X#c#pa#a#.CQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQt#F#4#5#7abahafad#4#U#R#M#N#N#F#K#2akak#9.v.vaa.w.w.w.u.u.u.k.\
k.f.X.f.8ag#U#c.f.7.e.e.e#u.B#v#h##.E#u.Qa.ar.U#h.Y.oaz.P#B#w#a.t.z#a#w.S.K.U.\
s#Q#K#M#S#Lak.j.v.Y.faqaj#U#4aj#U#4a..C#K#4#5ab.wa.#Faqasagahafajac.g.g.C#BawQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQt.i#5#6#8aq#4aeadad#Y#L#M#K#F#K#J#J#O.v.v.vaa.w.w.w.u.j.k.k.y#\
V.f.X.z.x#Uagas#..f#h.m#B#w.baA#f.EaB.1aB.b.M.D.K#ua##n#k.U.l.o#x#w.r.y#M#U#8#\
U#T.w.f.J.v#Laaab#M.T.P#9#8#6aiax#Uab#b.D#Q#5#5#3#Y.Eaa#4asaead#4.waC.S.Ea#.Qa\
DQtQtQtQtQtQtQtQtQtQtQt",
".cQtQtQtQtQtQtQt.9ai#Y#U#7aiaeab#3#5#L#N#K#F#K#2#9#O.v.v.v.w.w.w.u.k.k#V.f.f.\
f.Y.Y#y.v.Yabagaf.f#p#hal#x.O#taBay.C.Q.b#A.B#I.l.U#o#h.e#x#n.U.w#K#L#U#U#N#F#\
K#2#R.f#c#V#Y#8.l#K#U.D.4.w#6#4aias#Uah.8.Dak#Yaiabab#h.f#Y#Kab.U.vaEaF.nan.6.\
QQtQtQtQtQtQtQtQtQtQtQt",
".cQtQtQtQtQtQtQt#C#Y#8#S#U#4asah#3#4#L#N#F#F#Q#O#O.vaa.v.w.w.x.u.k.k.f.f.X.X.\
X.X.W.W.U.W#5#3afag.X.t#u.d.b.C.E.o.7#C.K.t.t.G.F#B.b#j.y#N#T#M#2.s.v.w.f.w#K#\
4#O#R#4.vaDac.v#8.U#Fab.b.4.x#8#5#5ax#8abaaay.w#U#U#7ajaw#c.f.E.RaGaHaIaJaD.Ca\
.arQtQtQtQtQtQtQtQtQtQt",
".cQtQtQtQtQtQtQt.Caa#Uaj#Tad#4ax#3#4#R#K#K#Q#J#2#9.v.s.s.w.w.u.k.y.f.X.X.f.Y.\
Y.Y#p.8.g.f.u#5aiafaf#a.9.4#r.b.0.H#o#n.6.Q.m##.U.s#Q#N#S#U#L#9.u#9#..W#Nai#K.\
w#Y.w.8#UaaaK.Bak#Y.s#Kab.K.M.u#Rai#Yax#7#3#K.P.f#M.t#L.MaE.qaLaMaMaIaIaJaJaN.\
CayQtQtQtQtQtQtQtQtQtQt",
".cQtQtQtQtQtQtQt.c#G#S#L#N#6#Yagab#3#U#Q#F#F#O#Oak.v.s.w.w.u.k.y.f.X.X.f.Y.W#\
..z.V.H#a.8.H#8#O#P.0.o.H.8.t#H.e#A#A.E#i.u#F#O#L#K.v.w.w.X.v.f#F#4.w.Hay.z#M#\
G.W#8#L.u#Y#M.3#uak#8aj#L#3#zau.j#Mai#Yah#Q#6.GaG#p.Q.naOaIaMaIaFaIaIaJaIaJaJa\
Cac.nQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQt.8#T#M#Q#Z#Yafab#3#Y#Q#Q#O#Oak.vaa.w.u#G.k.f.f.X.W.J.U#c.V.\
t#k#i.K.S#a#m#q#D#y#..H#0a#.R.m.K.8#J#R#R#N#M#M#2ak#J.8.W.u#4#L.W.8#L#VaOaN.U#\
K#K.x#Y#6#F#Y#Uau#u#9#Rad#Tab.U.M.k#M#J#R.Y.l#jaIaPaEaIaQaQaRaIaQaHaQaMaQaMaFa\
va##vQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQt#c#L#Q#J#K#6aiab#3ai#K#O#9#O#O.vaa.u.j.k.X.W.8.z.I.I.9.H#D#\
h.e.a.e#a#c.k.z.K.6.D.D#I#o.k.v.x#O#Q#U#Z.x#K#Y.u#Kad.w.U.S.S#J#R.e#.#L.vaOaS.\
Y#N#S#Q#7ab#8#5#U.4.D#9#Rad#L#4##.1.f.jap.zaC#taQaIaQaQaIaQaIaRaIaQaFaIaT.6.u#\
Q.g.lQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQt.q#Q#Q#O#2#5#Raf#3ai#L#O.v#2.v.v.w#V.X#..J.J.z.t#l#q.Ea##1#\
m#c.i.U.L.Say.q.m#a.i#Q#Nak#K.v.f#G.k#J#Rak.vad#L.u.f#L#G.#aI.Sak#Y.b#V#L.waDa\
K.k#N#6#T#6ah#Y#Y#8.nay#9#M.U#2.ZaHaD.GaCaHaIaUaIaQaQaQaRaIaRaIaQaIaK#a#N#T#Ua\
f.w##QtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQt#r.Y#2akak#Z#Laf#3#4#Zak#9aa.u.k.Y.W#p.J.H.K#C#v.e.K#c.h.Z#\
z#Ca#.q#A#C.z.u#9#J#L#Q#Rakak#Q.x.8.8.yai#Uaa.l#L#L#B.f#T.vaSaF.Lak#Y#C.w#R.wa\
V#g.w#Kab#U#6ab#U#8#J#E.Q#Q.Taw.9aFaMaQaIaQaRaIaUaQaRaQaQaRaIaIaw.z#Z#K.x.f.s#\
3#j.4QtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQt.H.v.vaa#K#U#5#3#5#S.s.y.f.k.Y#..l#m#I.b.K#c#V.f.H.0.eay.\
D#W#i.k#Q#M#9aa.y.y#Q#G#R.uaa#U#6.Y.W#H.6#Q#M#n.r#2#4.E.v#S.yaWaX.Uak#7#h#9#S.\
uaWaw.v#Kab#R#5#O.k#Y#gaM#u#xaIaIaIaRaFaQaQaIaUaQaUaQaQaQaL.D.j#U#9.y.W.Y.j#La\
a.SQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQt.laa.w.w#O#7akas#Y#R.v#..U#j##.T#a#P.u.u.U#a#Wa#an.e.L.f#\
Q#R#T#R#Q#R#9.v.U#P.y#2#5#N.k.x#6#Q.7aLaI.Fak#4#h.X#Q#5#C#Q#Y#paPaW#V#O#7#m#J#\
8.faP#uak#J#c.v#LaG.xacaMaIaRaIaQaIaIaQaMaQaQaIaUaIaUaW.7#N#L.u.Y.U.X.k#V.H#b.\
SaNQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQt#u.u.x.x.w#Z.x#J#4.v.z#m#D#y.x#9.f.H#h.ea##v#d.Jak#T#U#U#\
L#L#Q#8.h#F#9#Yaa#..X.u#M#U.uaK.S#J#5.maLaM#iakab#Iak#M#R#b#J#5.HaLaY.s#2#U.la\
k#Z.KaH#B#Q.l#g#VaSaFaIaQaIaIaQaMaQaIaIaQaIaQaQaIaB#j#R#2.f.U#c.W.u.Y#i.qQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt#o#G.u.u#K#M.t.Y#T#L#Q.v.i#l.o#x.e#h.t.u#Q#Q.v#Q#K#M#M#\
K#9.s#U#8.w#Qas#N.fayaOaN.u#L#2aV.U#Q#4.OaFaN.y#O#4#q#Q#Z#O#c#O#4##aH#rak#Q.y#\
a#J#GaHaI.e.KaIaRaHaRaIaIaRaIaIaQaIaQaQaIaRaZ.O.8#R.u#..z.9.Y.w.f.rapQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt.K.k#G.u.v#U#P.H#z#z#l#D#a#n#m.f#Q#M#R#T#R#Q.x.u.y.v#Q#\
7#Kaa#6ab.w#k.H#M#F.qaHaI.O#Q#7#.aKak#N#R.1aF.d#J#K#R#D#J#7.k.f#2#4#vaH.Qak#8a\
G.r#2aWaHaQaQaHaQaQaHaQaQaIaQaIaIaQaIaQaN#v.u#L.X#c.H.t.Y.w.f.g#xQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt#I#V.k.j.w#T.f.H#z#l#D#a#a###G#7#R#M#R#R#U#Q#..Y#V.u#Ta\
s#N#G.L#U#F.taT.x#R#Y.NaXaI.K#O#4#h.q#Q#R#GaWaMa##J#Taa#c#2#4.J.w#Q.uaLaM.S#U.\
naC#gaIaQaMaQaQaHaQaQaHaQaIaIaQaIaMaO.0#J#9.8#o#l.H.X.s.f.l#BQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtaG.J.f.k.u#O#Q#k.l#l#b#a#m#d.H#8#L#Oaaaa#U#4#U#V.wak.Z#\
Q#T.k.##h#Mab#hal#L#7.waNaFaE.u.v#3ap#a#O#7.HaCaF.L.v#U.Z.y#2#Nayak#YaEaFaI#Xa\
0aQaQaHaQaQaHaQaQaHaQaQaHaRaIaX#g.9#K#G.z.l#a.H.f.s.Y.H.eQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQt#a.h.k.jaa#T.I.l.L#a#H#m##.T#9#Q#6#N.w#Rag#Uaaa#.daF#\
r#R#6.fa0.v#Mab.O.g#F#3#aaFaH.A#M#K#R#g.fak#4.EaLaP.f.w#Q.Q.s#7.A.p.waYaQaFaQa\
QaFaQaQaMaQaQaHaQaRaFaQaIaNap.X#L.f.V#a.K.H#V.w#y#aa#QtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQt#n.Y.k.k.x#K.h.l.L#D#H.K###h.Uaiaf#T#O#k.X#U#K.paMaPa\
L#k#Nah.b.p#S#8#F#f#9#J#4.BaXaF#C#Q#S.y.4#F#2#Y#gaHaBak#U.R.4#2.QaQaZaIaRaQaMa\
RaIaHaRaQaHaQaQaMaQaJaO.e.v#O.8.H#a#d.9.j.w.U.g.4QtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQt#g.U#V.k.uak#Q#i.g#b#m#d###h#m#Nah#U.WaX#f#Yai#LaWaPa\
XaY#R#L#4#e.9#Fad.H.q#R#L#TaDaFaP.Y.vai#a.m#K#Q.GaFaIaw#L.GaRaXaFaQaQaIaIaQaIa\
IaRaIaFaQaQaHaQaQav.K#K.w.V#a.T.0#c.x.x.z.T.BQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQt#a#V#V.j.x#L.I.L#a.K#d##.T.o#e#c#Uab.6aL.l#Zas#laFa\
NaC.o#Rai.jaY#T#Fab#A.H#Q#6.8aLaF#f#Lak.saO.l#R.zaQaLaI#EaLaFaQaQaFaQaQaHaQaQa\
MaIaQaIaMaQaIaz#y#R.f#i##.o#h#y.x.u.I#IaYQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQt.6.Y.f.y.u#9.f#l#a.K#d##.T.o.Parai#4#4aO#f#U#Uab.4a\
XaPaT#9#Qah#w.e#Z#S#Rau#Q#O#3.eaCaF#B#Mai#gaC.Y.UaCaIaLaUaQaMaIaQaQaMaQaQaFaRa\
RaFaIaIaP#A.u#L.Z.g#d.o#n.8.w.X.Ha#.dQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtaT.t.f.y.j.u#F.l#a.K#d#n.T.o#1aT#.#8ax.HaP.K#8ad.wa\
Za1aX.q#6#T#4#g.f#Q#4.U.Q#U#Q.iaHaCaH.K#6#0aJaIaZaIaQaIaFaQaQaLaQaQaIaIaQaQaHa\
QaQaB#w#K#Q#y#a#C.b#m.i.v.Y#i.QQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQt#o.f.f.j.u#F.I#b.K##.T#h.o.E.d#rab#7as.MaK#T#Ras.\
EaXaEaP.U#Kai.Yar#U#J#K.A#o#R#4aEaFaLa2.2aSaIaRaIaXaQaRaHaIaQaQaFaQaQaMaIaQaF#\
g.g#Raa#k.K.o.S#m.Y.w.i.H.CQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQt.q#p.f.k.u.w#G#D.K#n.T#q.7.E.qaW.U#6as.kaE#I#4#6#\
7#taEaX.d#U#J#4.D.T#Z#4#xaW.k#4.qaIaXaIaQaQaXaRaQaIaHaQaQaFaIaQaIaLaQaQaN.n#.#\
U.k.l.0.o.S#D.Y.u.U.l.OQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQt.c.L.h.k.u#G#F#l#m###h#C#I#W#vaVazab#Uaf.QaG#9#Ra\
b.taLa0aC.T#U#M.Ha0.Wai.JaFaK.qaFaJaIa2aRaUaIaFaQaQaFaIaQaQaFaQaRaFaW.Q.u#L.W.\
l.G#I#w#j.f#G.z.T.nQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#C.h.k#G.x#9.U#H###h#C#I#W.6.2aT.z#5ab#MaT.a#4#\
Rad.naPaEaT.x#Y#OaXaD.t.eaIaIaFaXaIaQaMaFaRaQaFaIaQaQaCaQaQaIa2aW.S#K#M.Z#l.T#\
w.o.H#V#G#c#bazQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.2#P.k#G.x.kaa#H##.T.o#I#W.e.DaP.n#4#8ax#0aV.f#\
U#L.KaFaWaL#f#T#Q#faIaIaXaHaIaJaXaFaJaQaXaIaQaQaXaQaQaIaCaI.1#b#K#K.8.L#n.o#h.\
I.k.k.U#b.AQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.l.y.j.x.u#Q.l#d.T.o#I#W.e.a.daW#z#4aiaaaT.p#\
6ai.xaFaLaNaI.#aNaNaIaIaQaZaIaJaIaCaIaJaJa2aQaQaIaXaQaM.p.H#R#J#.#j##.o##.U.u.\
y.H#a.DQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtac.Z.k#G.s#G.X.K.T.o.7#W.ea#.eaE.M#7#U#8#raE.\
o#4aiauaHaPaLaIaIaLaXaIaIaHaLaIaIaMaXaJaJaMaXaQaQ#E.D.f#8.w.U#l.K.T#D.W.u.h.H#\
W#gQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtaE#z.k#G.x.f#Q#a#n#0.7#W.ea..e.pa1#nabai#haLa\
C#nanaXaHaMaNaIaIaIaPaIaIaIaCaHaIaQaXaHaJaJaEaV#v#O#T.Y.H#a#n.G#j.h.x#V#l#x#rQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.6.y.u.x.x.s#c###h#I#W#1a.ay#iaPaW.W#6.faZa\
FaFa1aFaHaMaXaCaIaIaMaPaIaIaIaZaIaIaIaEaIaG#l#L#K.J#D#n#h#h#k.j.u.f.l.E.3QtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.4.H.k.x.w.X.s###h.o.b#x.6.Q#D#uaLaG.1.1aCa\
FaFaFaNaHaIaIaPaIaIaIaCaXaIaIaFaXaIaF.B.I#8ak.I#a.T#w.o.9.x.u.f#j.eaGQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQta.#G.u.x#Gak.l.T#C#w.E.ea#a#.JaZaLaFaCaWa\
FaFaFaPaLaMaMaFaPaIaIaIaNaIaIaIaB.q.h#6.u.H###C.o#h#y.w.j.f#i#vQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtaZ#o.u.x.s.f.h#n.o#w.E.e.a.R.YawaXaLaFa1a\
PaFaHaFa1aMaMaIaPaFaIaIaFaWaG#I#Q#Z.Y#l.G.7.E.T.W.v.x.W#D#BQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#1.u.x.w#V#2#a#q.7#W#1.aao#a.raPaFaFaX#\
EaFaFaFaZaCaHaMaMaNaIaF.d.H#R#M.U#D#h.b.E.G.W.v.u.k#l.PQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtaD.U.x.w.w.j#..T.o.b#x.m.Qa#.u.4aLaLaLa\
EaEaFaFaFa1aHaIaI#t.p.I#U#O#y#a#q#w.E#m.X.v.x.Y.L.EQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.G.w.w.v.h#9#d.o#w#x.aan.R.u.oaNaXaFa\
FaTaFaFaFaCaWaW.Qaa#8aa.9#m#0.b#W#D.yak.u.J#b.EQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtaV#y.s.s.w.s.I#h#w#1a.a#.Q.l.W.4aLaFa\
HaPa1aFaF#f#H#9#U.y.H#H#h#w#w.l.u.w.x.U#bacQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.o.w.vak.faa###w.ea..aan.e#Y.ba1aFa\
FaF#f.2#l#U#Z.y#k#m#C#w.o.V.w.x.x#c.KalQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtav.zaa.v.xak.H.o#xa..ma#a##Z.ZawaXa\
0.q#G#6#R.f.H#H#h.7.T#caa.w.u.U.m.dQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#w.w.v#9.f.x#0.E.ea..a.a.yab.o#w#\
Qab#L.f#k#a.T#q.K.W.v.x#G#o#v.PQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.c.Iakak.j#2#D#W.e#va.a..Vatafab#\
M.X.t#D.K.G.L.f#O.u.y.H#wavQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.Kaa#O#O#V.j.o.e.ea..e.T#T#K.X.\
z.l#a.K.H.x#O.x#V.U.eQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.J#O#O.u#Q#D#W.e#v.6.e#m.U.H.\
r#l#yaa#9.x.f.U.eQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.F.s#2#O.s.u#C#x.e#w.r.W#k.l.\
8#9#O.w.i.l.6QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.Z#2#Q#2#4.u#i#k.k#L#S.u#J#\
2aa.Y#a.qQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.D#V#Q#Kaiab#Raj#8#Mak#Q#O.\
Y.g.DQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.T#J#K#U#4#4#R#Q.v.x.f#a.\
mQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.5.V#K#U#5#Y#Q.v.w.U.pQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.q.f#S#Y#S.v#V#H#xQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#h.W.w.i#b.DaNQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQta3.aac.cQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt"
};
static Fl_Pixmap image_stygmicon128(idata_stygmicon128);

void about::cb_Close_i(Fl_Button*, void*) {
  aboutwin->do_callback();
}
void about::cb_Close(Fl_Button* o, void* v) {
  ((about*)(o->parent()->user_data()))->cb_Close_i(o,v);
}

about::about() {
  Fl::visual(FL_DOUBLE|FL_INDEX);
Fl::visual(FL_RGB);

static const char *pepe [] ={"stygmorgan"};
char temp[64];
int argc=1;
char **argv= (char **) pepe;



make_window();

aboutwin->position(x+100,y+160);

bzero(temp,sizeof(temp));
sprintf(temp, "About %s",PACKAGE);

aboutwin->copy_label(temp);

aboutwin->icon((char *)p);

aboutwin->show(argc,argv);

bzero(temp,sizeof(temp));
sprintf(temp, "%s %s",PACKAGE,VERSION);
progname->copy_label(temp);

Fl_Text_Buffer *buf = new Fl_Text_Buffer(2000);
Fl_Text_Buffer *buf1 = new Fl_Text_Buffer(20000);
Fl_Text_Buffer *buf2 = new Fl_Text_Buffer(1000);
Fl_Text_Buffer *buf3 = new Fl_Text_Buffer(1000);
Fl_Text_Buffer *buf4 = new Fl_Text_Buffer(1000);

bzero(temp,sizeof(temp));
sprintf(temp,"%s/AUTHORS",HELPDIR);
buf->insertfile(temp,1);
TDA->buffer(buf);

bzero(temp,sizeof(temp));
sprintf(temp,"%s/LICENSE",HELPDIR);
buf1->insertfile(temp,1);
TDL->buffer(buf1);

bzero(temp,sizeof(temp));
sprintf(temp,"%s/THANKS",HELPDIR);
buf2->insertfile(temp,1);
TDTh->buffer(buf2);

bzero(temp,sizeof(temp));
sprintf(temp,"%s/DISCLAIMER",HELPDIR);
buf3->insertfile(temp,1);           
TDD->buffer(buf3);

bzero(temp,sizeof(temp));
sprintf(temp,"%s/TRANSLATE",HELPDIR);
buf4->insertfile(temp,1);
TDT->buffer(buf4);
}

Fl_Double_Window* about::make_window() {
  { aboutwin = new Fl_Double_Window(625, 370);
    aboutwin->color(FL_BACKGROUND2_COLOR);
    aboutwin->callback((Fl_Callback*)cb_aboutwin, (void*)(this));
    { Fl_Tabs* o = new Fl_Tabs(0, 0, 615, 330);
      o->color(FL_BACKGROUND2_COLOR);
      { Tab1 = new Fl_Group(0, 30, 600, 295, gettext("About"));
        Tab1->color(FL_BACKGROUND2_COLOR);
        Tab1->selection_color(FL_BACKGROUND2_COLOR);
        { progname = new Fl_Box(45, 150, 525, 40);
          progname->labelfont(1);
          progname->labelsize(22);
          progname->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
        } // Fl_Box* progname
        { new Fl_Box(20, 185, 565, 40, gettext("A Interactive Music Workstation Software"));
        } // Fl_Box* o
        { new Fl_Box(155, 220, 305, 25, gettext("(c) 2006, Josep Andreu"));
        } // Fl_Box* o
        { Fl_Box* o = new Fl_Box(65, 75, 505, 60);
          o->image(image_stygmicon128);
        } // Fl_Box* o
        Tab1->end();
      } // Fl_Group* Tab1
      { Tab2 = new Fl_Group(0, 30, 615, 300, gettext("Authors"));
        Tab2->color(FL_BACKGROUND2_COLOR);
        Tab2->selection_color(FL_BACKGROUND2_COLOR);
        Tab2->hide();
        { TDA = new Fl_Text_Display(5, 35, 605, 290);
        } // Fl_Text_Display* TDA
        Tab2->end();
      } // Fl_Group* Tab2
      { Fl_Group* o = new Fl_Group(0, 30, 615, 300, gettext("Thanks to"));
        o->color(FL_BACKGROUND2_COLOR);
        o->selection_color(FL_BACKGROUND2_COLOR);
        o->hide();
        { TDTh = new Fl_Text_Display(5, 35, 605, 290);
        } // Fl_Text_Display* TDTh
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 30, 615, 300, gettext("Translate"));
        o->color(FL_BACKGROUND2_COLOR);
        o->selection_color(FL_BACKGROUND2_COLOR);
        o->hide();
        { TDT = new Fl_Text_Display(5, 35, 605, 290);
        } // Fl_Text_Display* TDT
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 30, 615, 300, gettext("License"));
        o->color(FL_BACKGROUND2_COLOR);
        o->selection_color(FL_BACKGROUND2_COLOR);
        o->hide();
        { TDL = new Fl_Text_Display(5, 35, 605, 290);
        } // Fl_Text_Display* TDL
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 25, 615, 305, gettext("Disclaimer"));
        o->hide();
        { TDD = new Fl_Text_Display(5, 30, 605, 295);
        } // Fl_Text_Display* TDD
        o->end();
      } // Fl_Group* o
      o->end();
    } // Fl_Tabs* o
    { Fl_Button* o = new Fl_Button(530, 340, 85, 25, gettext("Close"));
      o->callback((Fl_Callback*)cb_Close);
    } // Fl_Button* o
    aboutwin->end();
  } // Fl_Double_Window* aboutwin
  return aboutwin;
}
